TYPE_LIGHT_SENSOR = 0
TYPE_SOIL_SENSOR = 1
TYPE_HUMIAIR_SENSOR = 2
TYPE_TEMP_SENSOR = 3
TYPE_DIGITAL_OUTPUT = 4

HEADER_CREATE = 0
HEADER_DELETE = 1
HEADER_SENSOR_VALUE = 2
HEADER_CONTROL_DEVICE = 3
HEADER_GET_DEVICE = 4
HEADER_CREATE_SCHEDULER = 5
HEADER_ACK = 6
HEADER_GET_SCHEDULER = 7